dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.3.2  # For Bluetooth communication
  nfc_manager: ^3.2.1  # For NFC payments
  sms_maintained: ^0.2.5  # For SMS-based transactions
  flutter_secure_storage: ^9.0.0  # Securely store payment data
  provider: ^6.1.0  # State management
  dio: ^5.3.2  # API requests
  firebase_core: ^2.15.0  # For optional cloud sync
  firebase_auth: ^4.11.1  # User authentication
  sqflite: ^2.2.8+4  # Local database
  intl: ^0.18.1  # Date and currency formatting
  qr_flutter: ^4.1.0  # QR Code for transactions
